# Your workflow name.
name: Deploy to Render

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Install Render CLI
        run: |
          wget -qO- https://render.com/install.sh | sudo bash


      - name: Set up Render environment
        run: render setup


      - name: Login to Render
        run: |
          $HOME/.render/render login --api-key ${{ secrets.RENDER_API_KEY }}


      - name: Build and Deploy to Render
        run: |
          render build --file Dockerfile
          render deploy --service ${{ secrets.RENDER_SERVICE_NAME }}



### ⬆ IMPORTANT PART ⬆ ###