# Your workflow name.
name: Deploy to Render

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Render
        uses: render-actions/deploy@v1
        with:
          # Render API key associated with your account.
          render_api_key: ${{ secrets.RENDER_API_KEY }}

          # Name of the Render service to which the build is to be sent.
          render_service_name: ${{ secrets.RENDER_SERVICE_NAME }}

          # (Optional, default: "./")
          # Dockerfile directory.
          dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_options: "--no-cache"



### ⬆ IMPORTANT PART ⬆ ###