# Your workflow name.
name: Deploy to Render

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Install Render CLI
        run: |
          curl -L https://render.com/install.sh | bash

      - name: Login to Render
        run: render login --api-key ${{ secrets.RENDER_API_KEY }}

      - name: Deploy to Render
        run: render deploy --service ${{ secrets.RENDER_SERVICE_ID }} --file Dockerfile --branch main

          
             
### ⬆ IMPORTANT PART ⬆ ###