# Your workflow name.
name: Deploy ML Model

# Run workflow on every push to main branch.
on:
  push:
    branches:
      - main

# Your workflows jobs.
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check-out your repository.
      - name: Checkout code
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t userharshada/prediction_model:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: userharshada
          password: hapatade45
          email: harshadapatade1999@gmail.com

      - name: Push Docker image
        run: docker push userharshada/prediction_model:latest

      - name: Deploy to web application
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app



### ⬇ IMPORTANT PART ⬇ ###