# Your workflow name.
name: Deploy Web App

# Run workflow on every push to main branch.
on:
  push:
    branches:
      - main

# Your workflows jobs.
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-docker-repo/your-app:latest

    - name: Deploy app
      uses: appleboy/ssh-action@master
      with:
        host: your-server-ip
        username: your-ssh-username
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker-compose down
          docker-compose pull
          docker-compose up -d


          
### ⬇ IMPORTANT PART ⬇ ###